//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNMReport.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DNMReportEntities1 : DbContext
    {
        public DNMReportEntities1()
            : base("name=DNMReportEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ReportProfile> ReportProfiles { get; set; }
        public DbSet<ReportSchedule> ReportSchedules { get; set; }
        public DbSet<ReportTask> ReportTasks { get; set; }
        public DbSet<ScheduleAction> ScheduleActions { get; set; }
        public DbSet<ScheduleTrigger> ScheduleTriggers { get; set; }
    }
}
