//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNMReport.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportProfile
    {
        public long ReportID { get; set; }
        public string ReportName { get; set; }
        public string ReportPathUploaded { get; set; }
        public string FileExtension { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime CreateTimeUtc { get; set; }
        public System.DateTime LastModifiedTime { get; set; }
        public System.DateTime LastModifiedTimeUtc { get; set; }
        public string LastModifiedUser { get; set; }
    }
}
