//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNMReport.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSchedule
    {
        public long ScheduleID { get; set; }
        public int TriggerId { get; set; }
        public string NAME { get; set; }
        public string Description { get; set; }
        public Nullable<int> ActionId { get; set; }
        public string Minute { get; set; }
        public string Hour { get; set; }
        public string Day { get; set; }
        public string Date { get; set; }
        public string Month { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime CreateTimeUtc { get; set; }
        public System.DateTime LastModifiedTime { get; set; }
        public System.DateTime LastModifiedTimeUtc { get; set; }
        public string LastModifiedUser { get; set; }
    }
}
